[
simd_i16x8_extadd_pairwise_i8x16
.
wast
.
js
.
html
]
[
#
25
Test
that
WebAssembly
instantiation
succeeds
]
expected
:
FAIL
[
#
28
run
]
expected
:
FAIL
[
#
31
run
]
expected
:
FAIL
[
#
34
run
]
expected
:
FAIL
[
#
37
run
]
expected
:
FAIL
[
#
40
run
]
expected
:
FAIL
[
#
43
run
]
expected
:
FAIL
[
#
46
run
]
expected
:
FAIL
[
#
49
run
]
expected
:
FAIL
[
#
52
run
]
expected
:
FAIL
[
#
55
run
]
expected
:
FAIL
[
#
58
run
]
expected
:
FAIL
[
#
61
run
]
expected
:
FAIL
[
#
64
run
]
expected
:
FAIL
[
#
67
run
]
expected
:
FAIL
[
#
70
run
]
expected
:
FAIL
[
#
73
run
]
expected
:
FAIL
