[
simd_i32x4_dot_i16x8
.
wast
.
js
.
html
]
[
#
36
Test
that
WebAssembly
instantiation
succeeds
]
expected
:
FAIL
[
#
39
run
]
expected
:
FAIL
[
#
42
run
]
expected
:
FAIL
[
#
45
run
]
expected
:
FAIL
[
#
48
run
]
expected
:
FAIL
[
#
51
run
]
expected
:
FAIL
[
#
54
run
]
expected
:
FAIL
[
#
57
run
]
expected
:
FAIL
[
#
60
run
]
expected
:
FAIL
[
#
63
run
]
expected
:
FAIL
[
#
66
run
]
expected
:
FAIL
[
#
69
run
]
expected
:
FAIL
[
#
72
run
]
expected
:
FAIL
[
#
75
run
]
expected
:
FAIL
[
#
78
run
]
expected
:
FAIL
[
#
81
run
]
expected
:
FAIL
[
#
84
run
]
expected
:
FAIL
[
#
87
run
]
expected
:
FAIL
[
#
90
run
]
expected
:
FAIL
[
#
93
run
]
expected
:
FAIL
[
#
96
run
]
expected
:
FAIL
[
#
99
run
]
expected
:
FAIL
[
#
102
run
]
expected
:
FAIL
[
#
105
run
]
expected
:
FAIL
[
#
108
run
]
expected
:
FAIL
[
#
111
run
]
expected
:
FAIL
[
#
114
run
]
expected
:
FAIL
[
#
117
run
]
expected
:
FAIL
[
#
120
run
]
expected
:
FAIL
