[
simd_i16x8_q15mulr_sat_s
.
wast
.
js
.
html
]
[
#
34
Test
that
WebAssembly
instantiation
succeeds
]
expected
:
FAIL
[
#
37
run
]
expected
:
FAIL
[
#
40
run
]
expected
:
FAIL
[
#
43
run
]
expected
:
FAIL
[
#
46
run
]
expected
:
FAIL
[
#
49
run
]
expected
:
FAIL
[
#
52
run
]
expected
:
FAIL
[
#
55
run
]
expected
:
FAIL
[
#
58
run
]
expected
:
FAIL
[
#
61
run
]
expected
:
FAIL
[
#
64
run
]
expected
:
FAIL
[
#
67
run
]
expected
:
FAIL
[
#
70
run
]
expected
:
FAIL
[
#
73
run
]
expected
:
FAIL
[
#
76
run
]
expected
:
FAIL
[
#
79
run
]
expected
:
FAIL
[
#
82
run
]
expected
:
FAIL
[
#
85
run
]
expected
:
FAIL
[
#
88
run
]
expected
:
FAIL
[
#
91
run
]
expected
:
FAIL
[
#
94
run
]
expected
:
FAIL
[
#
97
run
]
expected
:
FAIL
[
#
100
run
]
expected
:
FAIL
[
#
103
run
]
expected
:
FAIL
[
#
106
run
]
expected
:
FAIL
[
#
109
run
]
expected
:
FAIL
[
#
112
run
]
expected
:
FAIL
