[
simd_select
.
wast
.
js
.
html
]
[
#
11
Test
that
WebAssembly
instantiation
succeeds
]
expected
:
FAIL
[
#
14
run
]
expected
:
FAIL
[
#
17
run
]
expected
:
FAIL
[
#
20
run
]
expected
:
FAIL
[
#
23
run
]
expected
:
FAIL
[
#
26
run
]
expected
:
FAIL
[
#
29
run
]
expected
:
FAIL
