[
cts
.
https
.
html
?
q
=
webgpu
:
shader
validation
extension
subgroup_size_control
:
enable_subgroup_size_control_requires_subgroups
:
*
]
[
:
enableSubgroups
=
false
]
[
:
enableSubgroups
=
true
]
[
cts
.
https
.
html
?
q
=
webgpu
:
shader
validation
extension
subgroup_size_control
:
subgroup_size_attribute_only_valid_in_compute_stage
:
*
]
[
:
stage
=
"
compute
"
]
[
:
stage
=
"
fragment
"
]
[
:
stage
=
"
vertex
"
]
[
cts
.
https
.
html
?
q
=
webgpu
:
shader
validation
extension
subgroup_size_control
:
subgroup_size_constant_value_must_be_power_of_2
:
*
]
[
:
size
=
0
]
[
:
size
=
1
]
[
:
size
=
100
]
[
:
size
=
128
]
[
:
size
=
15
]
[
:
size
=
16
]
[
:
size
=
2
]
[
:
size
=
256
]
[
:
size
=
3
]
[
:
size
=
32
]
[
:
size
=
33
]
[
:
size
=
4
]
[
:
size
=
48
]
[
:
size
=
5
]
[
:
size
=
64
]
[
:
size
=
65
]
[
:
size
=
8
]
[
:
size
=
9
]
[
cts
.
https
.
html
?
q
=
webgpu
:
shader
validation
extension
subgroup_size_control
:
subgroup_size_must_be_between_min_and_max_at_pipeline_creation
:
*
]
[
:
subgroupSizeIsOverride
=
false
;
relation
=
"
above_max
"
]
[
:
subgroupSizeIsOverride
=
false
;
relation
=
"
at_max
"
]
[
:
subgroupSizeIsOverride
=
false
;
relation
=
"
at_min
"
]
[
:
subgroupSizeIsOverride
=
false
;
relation
=
"
below_min
"
]
[
:
subgroupSizeIsOverride
=
true
;
relation
=
"
above_max
"
]
[
:
subgroupSizeIsOverride
=
true
;
relation
=
"
at_max
"
]
[
:
subgroupSizeIsOverride
=
true
;
relation
=
"
at_min
"
]
[
:
subgroupSizeIsOverride
=
true
;
relation
=
"
below_min
"
]
[
cts
.
https
.
html
?
q
=
webgpu
:
shader
validation
extension
subgroup_size_control
:
subgroup_size_override_must_be_power_of_2_at_pipeline_creation
:
*
]
[
:
size
=
0
]
[
:
size
=
127
]
[
:
size
=
15
]
[
:
size
=
3
]
[
:
size
=
31
]
[
:
size
=
5
]
[
:
size
=
63
]
[
:
size
=
7
]
[
cts
.
https
.
html
?
q
=
webgpu
:
shader
validation
extension
subgroup_size_control
:
subgroup_size_override_valid_values_no_error
:
*
]
[
:
]
[
cts
.
https
.
html
?
q
=
webgpu
:
shader
validation
extension
subgroup_size_control
:
subgroup_size_value_must_be_const_or_override_i32_u32
:
*
]
[
:
case
=
"
const_bool
"
]
[
:
case
=
"
const_expr_abstract
"
]
[
:
case
=
"
const_expr_named
"
]
[
:
case
=
"
const_f32
"
]
[
:
case
=
"
const_i32
"
]
[
:
case
=
"
const_u32
"
]
[
:
case
=
"
let_u32
"
]
[
:
case
=
"
literal_abstract_float
"
]
[
:
case
=
"
literal_abstract_int
"
]
[
:
case
=
"
literal_bool
"
]
[
:
case
=
"
literal_f32
"
]
[
:
case
=
"
literal_i32
"
]
[
:
case
=
"
literal_u32
"
]
[
:
case
=
"
override_expr
"
]
[
:
case
=
"
override_f32
"
]
[
:
case
=
"
override_i32
"
]
[
:
case
=
"
override_u32
"
]
[
:
case
=
"
var_u32
"
]
[
cts
.
https
.
html
?
q
=
webgpu
:
shader
validation
extension
subgroup_size_control
:
use_subgroup_size_attribute_requires_subgroup_size_control_extension_enabled
:
*
]
[
:
enableExtension
=
false
]
[
:
enableExtension
=
true
]
[
cts
.
https
.
html
?
q
=
webgpu
:
shader
validation
extension
subgroup_size_control
:
workgroup_size_x_must_be_multiple_of_subgroup_size_at_pipeline_creation
:
*
]
[
:
workgroupSizeIsOverride
=
false
;
subgroupSizeIsOverride
=
false
;
offset
=
-
1
;
multiplier
=
1
]
[
:
workgroupSizeIsOverride
=
false
;
subgroupSizeIsOverride
=
false
;
offset
=
-
1
;
multiplier
=
2
]
[
:
workgroupSizeIsOverride
=
false
;
subgroupSizeIsOverride
=
false
;
offset
=
-
1
;
multiplier
=
3
]
[
:
workgroupSizeIsOverride
=
false
;
subgroupSizeIsOverride
=
false
;
offset
=
0
;
multiplier
=
1
]
[
:
workgroupSizeIsOverride
=
false
;
subgroupSizeIsOverride
=
false
;
offset
=
0
;
multiplier
=
2
]
[
:
workgroupSizeIsOverride
=
false
;
subgroupSizeIsOverride
=
false
;
offset
=
0
;
multiplier
=
3
]
[
:
workgroupSizeIsOverride
=
false
;
subgroupSizeIsOverride
=
false
;
offset
=
1
;
multiplier
=
1
]
[
:
workgroupSizeIsOverride
=
false
;
subgroupSizeIsOverride
=
false
;
offset
=
1
;
multiplier
=
2
]
[
:
workgroupSizeIsOverride
=
false
;
subgroupSizeIsOverride
=
false
;
offset
=
1
;
multiplier
=
3
]
[
:
workgroupSizeIsOverride
=
false
;
subgroupSizeIsOverride
=
true
;
offset
=
-
1
;
multiplier
=
1
]
[
:
workgroupSizeIsOverride
=
false
;
subgroupSizeIsOverride
=
true
;
offset
=
-
1
;
multiplier
=
2
]
[
:
workgroupSizeIsOverride
=
false
;
subgroupSizeIsOverride
=
true
;
offset
=
-
1
;
multiplier
=
3
]
[
:
workgroupSizeIsOverride
=
false
;
subgroupSizeIsOverride
=
true
;
offset
=
0
;
multiplier
=
1
]
[
:
workgroupSizeIsOverride
=
false
;
subgroupSizeIsOverride
=
true
;
offset
=
0
;
multiplier
=
2
]
[
:
workgroupSizeIsOverride
=
false
;
subgroupSizeIsOverride
=
true
;
offset
=
0
;
multiplier
=
3
]
[
:
workgroupSizeIsOverride
=
false
;
subgroupSizeIsOverride
=
true
;
offset
=
1
;
multiplier
=
1
]
[
:
workgroupSizeIsOverride
=
false
;
subgroupSizeIsOverride
=
true
;
offset
=
1
;
multiplier
=
2
]
[
:
workgroupSizeIsOverride
=
false
;
subgroupSizeIsOverride
=
true
;
offset
=
1
;
multiplier
=
3
]
[
:
workgroupSizeIsOverride
=
true
;
subgroupSizeIsOverride
=
false
;
offset
=
-
1
;
multiplier
=
1
]
[
:
workgroupSizeIsOverride
=
true
;
subgroupSizeIsOverride
=
false
;
offset
=
-
1
;
multiplier
=
2
]
[
:
workgroupSizeIsOverride
=
true
;
subgroupSizeIsOverride
=
false
;
offset
=
-
1
;
multiplier
=
3
]
[
:
workgroupSizeIsOverride
=
true
;
subgroupSizeIsOverride
=
false
;
offset
=
0
;
multiplier
=
1
]
[
:
workgroupSizeIsOverride
=
true
;
subgroupSizeIsOverride
=
false
;
offset
=
0
;
multiplier
=
2
]
[
:
workgroupSizeIsOverride
=
true
;
subgroupSizeIsOverride
=
false
;
offset
=
0
;
multiplier
=
3
]
[
:
workgroupSizeIsOverride
=
true
;
subgroupSizeIsOverride
=
false
;
offset
=
1
;
multiplier
=
1
]
[
:
workgroupSizeIsOverride
=
true
;
subgroupSizeIsOverride
=
false
;
offset
=
1
;
multiplier
=
2
]
[
:
workgroupSizeIsOverride
=
true
;
subgroupSizeIsOverride
=
false
;
offset
=
1
;
multiplier
=
3
]
[
:
workgroupSizeIsOverride
=
true
;
subgroupSizeIsOverride
=
true
;
offset
=
-
1
;
multiplier
=
1
]
[
:
workgroupSizeIsOverride
=
true
;
subgroupSizeIsOverride
=
true
;
offset
=
-
1
;
multiplier
=
2
]
[
:
workgroupSizeIsOverride
=
true
;
subgroupSizeIsOverride
=
true
;
offset
=
-
1
;
multiplier
=
3
]
[
:
workgroupSizeIsOverride
=
true
;
subgroupSizeIsOverride
=
true
;
offset
=
0
;
multiplier
=
1
]
[
:
workgroupSizeIsOverride
=
true
;
subgroupSizeIsOverride
=
true
;
offset
=
0
;
multiplier
=
2
]
[
:
workgroupSizeIsOverride
=
true
;
subgroupSizeIsOverride
=
true
;
offset
=
0
;
multiplier
=
3
]
[
:
workgroupSizeIsOverride
=
true
;
subgroupSizeIsOverride
=
true
;
offset
=
1
;
multiplier
=
1
]
[
:
workgroupSizeIsOverride
=
true
;
subgroupSizeIsOverride
=
true
;
offset
=
1
;
multiplier
=
2
]
[
:
workgroupSizeIsOverride
=
true
;
subgroupSizeIsOverride
=
true
;
offset
=
1
;
multiplier
=
3
]
