[
cts
.
https
.
html
?
q
=
webgpu
:
shader
validation
expression
call
builtin
atomicStoreMinMax
:
atomic_ptr_parameterization
:
*
]
[
:
op
=
"
atomicStoreMax
"
]
[
:
op
=
"
atomicStoreMin
"
]
[
cts
.
https
.
html
?
q
=
webgpu
:
shader
validation
expression
call
builtin
atomicStoreMinMax
:
atomic_ptr_type
:
*
]
[
:
op
=
"
atomicStoreMax
"
]
[
:
op
=
"
atomicStoreMin
"
]
[
cts
.
https
.
html
?
q
=
webgpu
:
shader
validation
expression
call
builtin
atomicStoreMinMax
:
non_atomic
:
*
]
[
:
op
=
"
atomicStoreMax
"
;
addrspace
=
"
storage
"
;
atomic
=
false
]
[
:
op
=
"
atomicStoreMax
"
;
addrspace
=
"
storage
"
;
atomic
=
true
]
[
:
op
=
"
atomicStoreMax
"
;
addrspace
=
"
workgroup
"
;
atomic
=
false
]
[
:
op
=
"
atomicStoreMax
"
;
addrspace
=
"
workgroup
"
;
atomic
=
true
]
[
:
op
=
"
atomicStoreMin
"
;
addrspace
=
"
storage
"
;
atomic
=
false
]
[
:
op
=
"
atomicStoreMin
"
;
addrspace
=
"
storage
"
;
atomic
=
true
]
[
:
op
=
"
atomicStoreMin
"
;
addrspace
=
"
workgroup
"
;
atomic
=
false
]
[
:
op
=
"
atomicStoreMin
"
;
addrspace
=
"
workgroup
"
;
atomic
=
true
]
[
cts
.
https
.
html
?
q
=
webgpu
:
shader
validation
expression
call
builtin
atomicStoreMinMax
:
requires_extension
:
*
]
[
:
op
=
"
atomicStoreMax
"
;
enable
=
false
]
[
:
op
=
"
atomicStoreMax
"
;
enable
=
true
]
[
:
op
=
"
atomicStoreMin
"
;
enable
=
false
]
[
:
op
=
"
atomicStoreMin
"
;
enable
=
true
]
[
cts
.
https
.
html
?
q
=
webgpu
:
shader
validation
expression
call
builtin
atomicStoreMinMax
:
return_type
:
*
]
[
:
op
=
"
atomicStoreMax
"
]
[
:
op
=
"
atomicStoreMin
"
]
[
cts
.
https
.
html
?
q
=
webgpu
:
shader
validation
expression
call
builtin
atomicStoreMinMax
:
stage
:
*
]
[
:
op
=
"
atomicStoreMax
"
;
stage
=
"
compute
"
]
[
:
op
=
"
atomicStoreMax
"
;
stage
=
"
fragment
"
]
[
:
op
=
"
atomicStoreMax
"
;
stage
=
"
vertex
"
]
[
:
op
=
"
atomicStoreMin
"
;
stage
=
"
compute
"
]
[
:
op
=
"
atomicStoreMin
"
;
stage
=
"
fragment
"
]
[
:
op
=
"
atomicStoreMin
"
;
stage
=
"
vertex
"
]
[
cts
.
https
.
html
?
q
=
webgpu
:
shader
validation
expression
call
builtin
atomicStoreMinMax
:
value_parameter
:
*
]
[
:
op
=
"
atomicStoreMax
"
]
[
:
op
=
"
atomicStoreMin
"
]
