[
cts
.
https
.
html
?
q
=
webgpu
:
shader
validation
statement
swizzle_assignment
:
chained_swizzle
:
*
]
[
:
case
=
"
xx_x
"
]
[
:
case
=
"
xxyy_xy
"
]
[
:
case
=
"
xxyy_zxy_xy
"
]
[
:
case
=
"
xxyy_zxy_yz
"
]
[
:
case
=
"
xy_y
"
]
[
:
case
=
"
xyy_xy
"
]
[
:
case
=
"
xyy_yy
"
]
[
:
case
=
"
zy_xyx
"
]
[
cts
.
https
.
html
?
q
=
webgpu
:
shader
validation
statement
swizzle_assignment
:
dynamic_index_into_swizzle_view
:
*
]
[
:
swizzle
=
"
x
"
]
[
:
swizzle
=
"
xx
"
]
[
:
swizzle
=
"
xy
"
]
[
:
swizzle
=
"
xyz
"
]
[
:
swizzle
=
"
xyzw
"
]
[
:
swizzle
=
"
zxy
"
]
[
cts
.
https
.
html
?
q
=
webgpu
:
shader
validation
statement
swizzle_assignment
:
index_into_swizzle_view
:
*
]
[
:
swizzle
=
"
x
"
;
index
=
0
]
[
:
swizzle
=
"
x
"
;
index
=
1
]
[
:
swizzle
=
"
x
"
;
index
=
2
]
[
:
swizzle
=
"
x
"
;
index
=
3
]
[
:
swizzle
=
"
x
"
;
index
=
4
]
[
:
swizzle
=
"
xx
"
;
index
=
0
]
[
:
swizzle
=
"
xx
"
;
index
=
1
]
[
:
swizzle
=
"
xx
"
;
index
=
2
]
[
:
swizzle
=
"
xx
"
;
index
=
3
]
[
:
swizzle
=
"
xx
"
;
index
=
4
]
[
:
swizzle
=
"
xy
"
;
index
=
0
]
[
:
swizzle
=
"
xy
"
;
index
=
1
]
[
:
swizzle
=
"
xy
"
;
index
=
2
]
[
:
swizzle
=
"
xy
"
;
index
=
3
]
[
:
swizzle
=
"
xy
"
;
index
=
4
]
[
:
swizzle
=
"
xyz
"
;
index
=
0
]
[
:
swizzle
=
"
xyz
"
;
index
=
1
]
[
:
swizzle
=
"
xyz
"
;
index
=
2
]
[
:
swizzle
=
"
xyz
"
;
index
=
3
]
[
:
swizzle
=
"
xyz
"
;
index
=
4
]
[
:
swizzle
=
"
xyzw
"
;
index
=
0
]
[
:
swizzle
=
"
xyzw
"
;
index
=
1
]
[
:
swizzle
=
"
xyzw
"
;
index
=
2
]
[
:
swizzle
=
"
xyzw
"
;
index
=
3
]
[
:
swizzle
=
"
xyzw
"
;
index
=
4
]
[
:
swizzle
=
"
zxy
"
;
index
=
0
]
[
:
swizzle
=
"
zxy
"
;
index
=
1
]
[
:
swizzle
=
"
zxy
"
;
index
=
2
]
[
:
swizzle
=
"
zxy
"
;
index
=
3
]
[
:
swizzle
=
"
zxy
"
;
index
=
4
]
[
cts
.
https
.
html
?
q
=
webgpu
:
shader
validation
statement
swizzle_assignment
:
invalid_address_of_swizzle_view
:
*
]
[
:
]
[
cts
.
https
.
html
?
q
=
webgpu
:
shader
validation
statement
swizzle_assignment
:
invalid_component_mismatch
:
*
]
[
:
]
[
cts
.
https
.
html
?
q
=
webgpu
:
shader
validation
statement
swizzle_assignment
:
invalid_component_oob
:
*
]
[
:
]
[
cts
.
https
.
html
?
q
=
webgpu
:
shader
validation
statement
swizzle_assignment
:
invalid_duplicate_components
:
*
]
[
:
]
[
cts
.
https
.
html
?
q
=
webgpu
:
shader
validation
statement
swizzle_assignment
:
invalid_lhs_not_reference
:
*
]
[
:
lhs
=
"
const_vec
"
]
[
:
lhs
=
"
foo
(
)
"
]
[
:
lhs
=
"
vec4f
(
)
"
]
[
cts
.
https
.
html
?
q
=
webgpu
:
shader
validation
statement
swizzle_assignment
:
invalid_mixed_letter_schemes
:
*
]
[
:
]
[
cts
.
https
.
html
?
q
=
webgpu
:
shader
validation
statement
swizzle_assignment
:
invalid_type_mismatch
:
*
]
[
:
]
[
cts
.
https
.
html
?
q
=
webgpu
:
shader
validation
statement
swizzle_assignment
:
pointer_swizzle_assignment
:
*
]
[
:
use_pointer
=
false
;
requires_pointer_composite_access
=
false
;
use_compound
=
false
]
[
:
use_pointer
=
false
;
requires_pointer_composite_access
=
false
;
use_compound
=
true
]
[
:
use_pointer
=
false
;
requires_pointer_composite_access
=
true
;
use_compound
=
false
]
[
:
use_pointer
=
false
;
requires_pointer_composite_access
=
true
;
use_compound
=
true
]
[
:
use_pointer
=
true
;
requires_pointer_composite_access
=
false
;
use_compound
=
false
]
[
:
use_pointer
=
true
;
requires_pointer_composite_access
=
false
;
use_compound
=
true
]
[
:
use_pointer
=
true
;
requires_pointer_composite_access
=
true
;
use_compound
=
false
]
[
:
use_pointer
=
true
;
requires_pointer_composite_access
=
true
;
use_compound
=
true
]
[
cts
.
https
.
html
?
q
=
webgpu
:
shader
validation
statement
swizzle_assignment
:
valid
:
*
]
[
:
elemType
=
"
f32
"
;
vecSize
=
2
]
[
:
elemType
=
"
f32
"
;
vecSize
=
3
]
[
:
elemType
=
"
f32
"
;
vecSize
=
4
]
[
:
elemType
=
"
i32
"
;
vecSize
=
2
]
[
:
elemType
=
"
i32
"
;
vecSize
=
3
]
[
:
elemType
=
"
i32
"
;
vecSize
=
4
]
[
:
elemType
=
"
u32
"
;
vecSize
=
2
]
[
:
elemType
=
"
u32
"
;
vecSize
=
3
]
[
:
elemType
=
"
u32
"
;
vecSize
=
4
]
