schema
:
1
bugzilla
:
product
:
Core
component
:
"
General
"
origin
:
name
:
wasm2c_sandbox_compiler
description
:
wasm2c
Wasm
compiler
used
for
rlbox
sandboxing
url
:
https
:
/
/
github
.
com
/
WebAssembly
/
wabt
release
:
e197d0b7bd3fe426f5963ae540f4426a1d49e89f
(
2026
-
09
-
16T05
:
01
:
55Z
)
.
revision
:
e197d0b7bd3fe426f5963ae540f4426a1d49e89f
license
:
Apache
-
2
.
0
license
-
file
:
LICENSE
vendoring
:
url
:
https
:
/
/
github
.
com
/
WebAssembly
/
wabt
source
-
hosting
:
github
vendor
-
directory
:
third_party
/
wasm2c
exclude
:
#
dirs
-
cmake
-
docs
-
fuzz
-
in
-
fuzzers
-
include
/
wabt
/
interp
-
man
-
scripts
-
src
/
interp
-
src
/
template
-
test
-
third_party
-
wasm2c
/
benchmarks
-
wasm2c
/
examples
#
files
-
.
*
-
CMakeLists
.
txt
-
Contributing
.
md
-
Makefile
-
README
.
md
-
SECURITY
.
md
-
ubsan
.
blacklist
-
src
/
test
-
*
-
src
/
tools
/
s
*
-
src
/
tools
/
wasm
-
*
-
src
/
tools
/
wast
*
-
src
/
tools
/
wat
*
-
src
/
tools
/
wasm2w
*
-
src
/
wabt
.
post
.
js
-
third_party
/
wasm2c
/
requirements
-
dev
.
txt
-
wasm2c
/
wasm
-
rt
-
exceptions
*
-
wasm2c
/
README
.
md
patches
:
-
revert
-
cpp20
-
changes
.
patch
-
openbsd
-
no
-
strtod
-
l
.
patch
-
allow
-
guard
-
pages
-
with
-
clang
-
cl
.
patch
