#
This
Source
Code
Form
is
subject
to
the
terms
of
the
Mozilla
Public
#
License
v
.
2
.
0
.
If
a
copy
of
the
MPL
was
not
distributed
with
this
#
file
You
can
obtain
one
at
https
:
/
/
mozilla
.
org
/
MPL
/
2
.
0
/
.
Classes
=
[
{
'
cid
'
:
'
{
f29e6ab3
-
34b5
-
4746
-
a2be
-
20112ca2e386
}
'
'
contract_ids
'
:
[
'
mozilla
.
org
/
site
-
category
;
1
'
]
'
headers
'
:
[
'
/
toolkit
/
components
/
sitecategories
/
SiteCategory
.
h
'
]
'
legacy_constructor
'
:
'
new_site_category
'
}
]
