#
This
Source
Code
Form
is
subject
to
the
terms
of
the
Mozilla
Public
#
License
v
.
2
.
0
.
If
a
copy
of
the
MPL
was
not
distributed
with
this
#
file
You
can
obtain
one
at
http
:
/
/
mozilla
.
org
/
MPL
/
2
.
0
/
.
Classes
=
[
{
'
cid
'
:
'
{
f6fba2e7
-
316d
-
4efc
-
b35d
-
bdf001402dfc
}
'
'
contract_ids
'
:
[
'
mozilla
.
org
/
geolocation
/
service
;
1
'
]
'
singleton
'
:
True
'
type
'
:
'
mozilla
:
:
GeolocationService
'
'
headers
'
:
[
'
/
toolkit
/
components
/
geolocation
/
GeolocationService
.
h
'
]
'
processes
'
:
ProcessSelector
.
MAIN_PROCESS_ONLY
'
constructor
'
:
'
mozilla
:
:
GeolocationService
:
:
GetGeolocationService
'
}
]
