[
2d
.
reset
.
render
.
text
.
w
.
html
]
fuzzy
:
if
os
=
=
"
mac
"
:
maxDifference
=
0
-
1
;
totalPixels
=
0
-
4
expected
:
if
(
os
=
=
"
win
"
)
and
(
processor
=
=
"
x86_64
"
)
and
not
swgl
:
FAIL
if
(
os
=
=
"
android
"
)
and
not
swgl
:
FAIL
