#
XXX
(
krosylight
)
:
The
test
fails
without
the
testing
pref
see
bug
1888182
prefs
:
[
dom
.
events
.
testing
.
asyncClipboard
:
true
]
[
readText
-
denied
.
https
.
html
]
expected
:
if
(
os
=
=
"
android
"
)
and
not
debug
:
[
OK
CRASH
]
max
-
asserts
:
2
[
navigator
.
clipboard
.
readText
(
)
fails
when
permission
denied
]
expected
:
FAIL
