[
i8x16_relaxed_swizzle
.
wast
.
js
.
html
]
[
#
2
Test
that
WebAssembly
compilation
succeeds
(
i8x16_relaxed_swizzle
.
wast
:
3
)
]
expected
:
if
os
=
=
"
win
"
:
[
PASS
FAIL
]
if
os
=
=
"
linux
"
:
[
PASS
FAIL
]
[
#
9
Test
that
WebAssembly
compilation
succeeds
(
i8x16_relaxed_swizzle
.
wast
:
3
)
]
expected
:
if
os
=
=
"
win
"
:
[
PASS
FAIL
]
if
os
=
=
"
linux
"
:
[
PASS
FAIL
]
FAIL
[
#
12
Test
that
WebAssembly
instantiation
succeeds
(
wrapper
)
]
expected
:
if
os
=
=
"
win
"
:
[
PASS
FAIL
]
if
os
=
=
"
linux
"
:
[
PASS
FAIL
]
FAIL
[
#
15
Test
that
WebAssembly
instantiation
succeeds
(
wrapper
)
]
expected
:
if
os
=
=
"
win
"
:
[
PASS
FAIL
]
if
os
=
=
"
linux
"
:
[
PASS
FAIL
]
FAIL
[
#
18
Test
that
WebAssembly
instantiation
succeeds
(
wrapper
)
]
expected
:
if
os
=
=
"
win
"
:
[
PASS
FAIL
]
if
os
=
=
"
linux
"
:
[
PASS
FAIL
]
FAIL
[
#
21
Test
that
WebAssembly
instantiation
succeeds
(
wrapper
)
]
expected
:
if
os
=
=
"
win
"
:
[
PASS
FAIL
]
if
os
=
=
"
linux
"
:
[
PASS
FAIL
]
FAIL
[
#
24
Test
that
WebAssembly
instantiation
succeeds
(
wrapper
)
]
expected
:
if
os
=
=
"
win
"
:
[
PASS
FAIL
]
if
os
=
=
"
linux
"
:
[
PASS
FAIL
]
FAIL
[
#
1
Reinitialize
the
default
imports
]
expected
:
FAIL
[
#
8
Reinitialize
the
default
imports
]
expected
:
FAIL
[
#
10
Test
that
WebAssembly
instantiation
succeeds
]
expected
:
FAIL
[
#
13
run
]
expected
:
FAIL
[
#
16
run
]
expected
:
FAIL
[
#
19
run
]
expected
:
FAIL
[
#
22
run
]
expected
:
FAIL
[
#
25
run
]
expected
:
FAIL
