[
address64
.
wast
.
js
.
html
]
[
#
38
Test
that
WebAssembly
instantiation
succeeds
]
expected
:
FAIL
[
#
249
run
]
expected
:
FAIL
[
#
252
run
]
expected
:
FAIL
[
#
255
run
]
expected
:
FAIL
[
#
258
run
]
expected
:
FAIL
[
#
261
run
]
expected
:
FAIL
[
#
264
run
]
expected
:
FAIL
[
#
267
run
]
expected
:
FAIL
[
#
270
run
]
expected
:
FAIL
[
#
273
run
]
expected
:
FAIL
[
#
276
run
]
expected
:
FAIL
[
#
279
run
]
expected
:
FAIL
[
#
282
run
]
expected
:
FAIL
[
#
285
run
]
expected
:
FAIL
[
#
288
run
]
expected
:
FAIL
[
#
298
run
]
expected
:
FAIL
[
#
301
run
]
expected
:
FAIL
[
#
304
run
]
expected
:
FAIL
[
#
307
run
]
expected
:
FAIL
[
#
310
run
]
expected
:
FAIL
[
#
313
run
]
expected
:
FAIL
[
#
316
run
]
expected
:
FAIL
[
#
319
run
]
expected
:
FAIL
[
#
322
run
]
expected
:
FAIL
[
#
325
run
]
expected
:
FAIL
[
#
328
run
]
expected
:
FAIL
[
#
331
run
]
expected
:
FAIL
[
#
334
run
]
expected
:
FAIL
[
#
337
run
]
expected
:
FAIL
