[
align64
.
wast
.
js
.
html
]
[
#
122
Test
that
WebAssembly
instantiation
succeeds
]
expected
:
FAIL
[
#
254
run
]
expected
:
FAIL
[
#
257
run
]
expected
:
FAIL
[
#
260
run
]
expected
:
FAIL
[
#
263
run
]
expected
:
FAIL
[
#
266
run
]
expected
:
FAIL
[
#
269
run
]
expected
:
FAIL
[
#
272
run
]
expected
:
FAIL
[
#
275
run
]
expected
:
FAIL
[
#
278
run
]
expected
:
FAIL
