[
endianness64
.
wast
.
js
.
html
]
[
#
21
Test
that
WebAssembly
instantiation
succeeds
]
expected
:
FAIL
[
#
56
run
]
expected
:
FAIL
[
#
59
run
]
expected
:
FAIL
[
#
62
run
]
expected
:
FAIL
[
#
65
run
]
expected
:
FAIL
[
#
68
run
]
expected
:
FAIL
[
#
71
run
]
expected
:
FAIL
[
#
74
run
]
expected
:
FAIL
[
#
77
run
]
expected
:
FAIL
[
#
100
run
]
expected
:
FAIL
[
#
103
run
]
expected
:
FAIL
[
#
106
run
]
expected
:
FAIL
[
#
109
run
]
expected
:
FAIL
[
#
112
run
]
expected
:
FAIL
[
#
115
run
]
expected
:
FAIL
[
#
118
run
]
expected
:
FAIL
[
#
121
run
]
expected
:
FAIL
