[
ice
-
ufragpwd
.
html
]
bug
:
2027782
#
WPTs
expect
the
wrong
error
type
[
setRemoteDescription
with
a
ice
-
ufrag
containing
a
non
-
ice
-
char
fails
]
expected
:
FAIL
[
setRemoteDescription
with
a
ice
-
pwd
containing
a
non
-
ice
-
char
fails
]
expected
:
FAIL
