/
*
This
Source
Code
Form
is
subject
to
the
terms
of
the
Mozilla
Public
*
License
v
.
2
.
0
.
If
a
copy
of
the
MPL
was
not
distributed
with
this
*
file
You
can
obtain
one
at
http
:
/
/
mozilla
.
org
/
MPL
/
2
.
0
/
.
*
/
#
include
"
nsISupports
.
idl
"
webidl
Element
;
/
*
*
*
Allow
applications
to
interface
with
the
Mac
OS
X
Sharing
APIs
.
*
/
[
scriptable
uuid
(
4a1e2b73
-
8c5d
-
4f6a
-
9b21
-
0c7de5a13f88
)
]
interface
nsIMacSharingService
:
nsISupports
{
/
*
*
*
Show
the
native
NSSharingServicePicker
anchored
to
the
given
DOM
element
.
*
The
picker
owns
the
list
of
providers
and
the
UI
.
macOS
invokes
the
*
service
that
the
user
chooses
.
*
*
urls
.
length
=
=
1
implies
a
single
-
tab
share
otherwise
the
share
item
exposes
*
text
/
html
structure
covering
all
URLs
.
shareTitle
populates
the
picker
'
s
*
preview
area
(
the
page
title
for
single
tab
share
or
"
Share
N
Links
"
for
multiple
)
.
*
/
void
shareUrlWithPicker
(
in
Element
anchor
in
Array
<
AString
>
urls
in
Array
<
AString
>
titles
in
AString
shareTitle
)
;
}
;
