[
cts
.
https
.
html
?
q
=
webgpu
:
shader
validation
shader_io
align
:
multi_align
:
*
]
[
:
multi
=
false
]
[
:
multi
=
true
]
[
cts
.
https
.
html
?
q
=
webgpu
:
shader
validation
shader_io
align
:
parsing
:
*
]
implementation
-
status
:
backlog
[
:
align
=
"
blank
"
]
[
:
align
=
"
comment
"
]
[
:
align
=
"
const_expr
"
]
[
:
align
=
"
const_expr_2
"
]
[
:
align
=
"
const_f
"
]
[
:
align
=
"
const_i
"
]
[
:
align
=
"
const_u
"
]
[
:
align
=
"
duplicate
"
]
[
:
align
=
"
empty
"
]
[
:
align
=
"
four_a
"
]
[
:
align
=
"
four_f
"
]
[
:
align
=
"
four_h
"
]
[
:
align
=
"
four_hex
"
]
[
:
align
=
"
four_i
"
]
[
:
align
=
"
four_u
"
]
[
:
align
=
"
large
"
]
[
:
align
=
"
large_no_power_two
"
]
[
:
align
=
"
larger_than_max_i32
"
]
expected
:
FAIL
[
:
align
=
"
missing_left_paren
"
]
[
:
align
=
"
missing_right_paren
"
]
[
:
align
=
"
misspelling
"
]
[
:
align
=
"
multiple_values
"
]
[
:
align
=
"
negative
"
]
[
:
align
=
"
no_params
"
]
[
:
align
=
"
non_power_two
"
]
[
:
align
=
"
one
"
]
[
:
align
=
"
one_f
"
]
[
:
align
=
"
tabs
"
]
[
:
align
=
"
trailing_comma
"
]
[
:
align
=
"
zero_a
"
]
[
cts
.
https
.
html
?
q
=
webgpu
:
shader
validation
shader_io
align
:
placement
:
*
]
[
:
scope
=
"
_undef_
"
;
attribute
=
{
"
private
-
var
"
:
false
"
storage
-
var
"
:
false
"
struct
-
member
"
:
true
"
fn
-
decl
"
:
false
"
fn
-
param
"
:
false
"
fn
-
var
"
:
false
"
fn
-
return
"
:
false
"
while
-
stmt
"
:
false
}
]
[
:
scope
=
"
fn
-
decl
"
;
attribute
=
{
"
private
-
var
"
:
false
"
storage
-
var
"
:
false
"
struct
-
member
"
:
true
"
fn
-
decl
"
:
false
"
fn
-
param
"
:
false
"
fn
-
var
"
:
false
"
fn
-
return
"
:
false
"
while
-
stmt
"
:
false
}
]
[
:
scope
=
"
fn
-
param
"
;
attribute
=
{
"
private
-
var
"
:
false
"
storage
-
var
"
:
false
"
struct
-
member
"
:
true
"
fn
-
decl
"
:
false
"
fn
-
param
"
:
false
"
fn
-
var
"
:
false
"
fn
-
return
"
:
false
"
while
-
stmt
"
:
false
}
]
[
:
scope
=
"
fn
-
return
"
;
attribute
=
{
"
private
-
var
"
:
false
"
storage
-
var
"
:
false
"
struct
-
member
"
:
true
"
fn
-
decl
"
:
false
"
fn
-
param
"
:
false
"
fn
-
var
"
:
false
"
fn
-
return
"
:
false
"
while
-
stmt
"
:
false
}
]
[
:
scope
=
"
fn
-
var
"
;
attribute
=
{
"
private
-
var
"
:
false
"
storage
-
var
"
:
false
"
struct
-
member
"
:
true
"
fn
-
decl
"
:
false
"
fn
-
param
"
:
false
"
fn
-
var
"
:
false
"
fn
-
return
"
:
false
"
while
-
stmt
"
:
false
}
]
[
:
scope
=
"
private
-
var
"
;
attribute
=
{
"
private
-
var
"
:
false
"
storage
-
var
"
:
false
"
struct
-
member
"
:
true
"
fn
-
decl
"
:
false
"
fn
-
param
"
:
false
"
fn
-
var
"
:
false
"
fn
-
return
"
:
false
"
while
-
stmt
"
:
false
}
]
[
:
scope
=
"
storage
-
var
"
;
attribute
=
{
"
private
-
var
"
:
false
"
storage
-
var
"
:
false
"
struct
-
member
"
:
true
"
fn
-
decl
"
:
false
"
fn
-
param
"
:
false
"
fn
-
var
"
:
false
"
fn
-
return
"
:
false
"
while
-
stmt
"
:
false
}
]
[
:
scope
=
"
struct
-
member
"
;
attribute
=
{
"
private
-
var
"
:
false
"
storage
-
var
"
:
false
"
struct
-
member
"
:
true
"
fn
-
decl
"
:
false
"
fn
-
param
"
:
false
"
fn
-
var
"
:
false
"
fn
-
return
"
:
false
"
while
-
stmt
"
:
false
}
]
[
:
scope
=
"
while
-
stmt
"
;
attribute
=
{
"
private
-
var
"
:
false
"
storage
-
var
"
:
false
"
struct
-
member
"
:
true
"
fn
-
decl
"
:
false
"
fn
-
param
"
:
false
"
fn
-
var
"
:
false
"
fn
-
return
"
:
false
"
while
-
stmt
"
:
false
}
]
[
cts
.
https
.
html
?
q
=
webgpu
:
shader
validation
shader_io
align
:
required_alignment
:
*
]
[
:
decl
=
"
const
"
;
address_space
=
"
function
"
;
align
=
"
alignment
"
]
[
:
decl
=
"
const
"
;
address_space
=
"
function
"
;
align
=
1
]
[
:
decl
=
"
const
"
;
address_space
=
"
function
"
;
align
=
2
]
[
:
decl
=
"
const
"
;
address_space
=
"
function
"
;
align
=
32
]
[
:
decl
=
"
const
"
;
address_space
=
"
private
"
;
align
=
"
alignment
"
]
[
:
decl
=
"
const
"
;
address_space
=
"
private
"
;
align
=
1
]
[
:
decl
=
"
const
"
;
address_space
=
"
private
"
;
align
=
2
]
[
:
decl
=
"
const
"
;
address_space
=
"
private
"
;
align
=
32
]
[
:
decl
=
"
let
"
;
address_space
=
"
function
"
;
align
=
"
alignment
"
]
[
:
decl
=
"
let
"
;
address_space
=
"
function
"
;
align
=
1
]
[
:
decl
=
"
let
"
;
address_space
=
"
function
"
;
align
=
2
]
[
:
decl
=
"
let
"
;
address_space
=
"
function
"
;
align
=
32
]
[
:
decl
=
"
var
"
;
address_space
=
"
function
"
;
align
=
"
alignment
"
]
[
:
decl
=
"
var
"
;
address_space
=
"
function
"
;
align
=
1
]
[
:
decl
=
"
var
"
;
address_space
=
"
function
"
;
align
=
2
]
[
:
decl
=
"
var
"
;
address_space
=
"
function
"
;
align
=
32
]
[
:
decl
=
"
var
"
;
address_space
=
"
immediate
"
;
align
=
"
alignment
"
]
[
:
decl
=
"
var
"
;
address_space
=
"
immediate
"
;
align
=
1
]
[
:
decl
=
"
var
"
;
address_space
=
"
immediate
"
;
align
=
2
]
[
:
decl
=
"
var
"
;
address_space
=
"
immediate
"
;
align
=
32
]
[
:
decl
=
"
var
"
;
address_space
=
"
private
"
;
align
=
"
alignment
"
]
[
:
decl
=
"
var
"
;
address_space
=
"
private
"
;
align
=
1
]
[
:
decl
=
"
var
"
;
address_space
=
"
private
"
;
align
=
2
]
[
:
decl
=
"
var
"
;
address_space
=
"
private
"
;
align
=
32
]
[
:
decl
=
"
var
"
;
address_space
=
"
storage
"
;
align
=
"
alignment
"
]
[
:
decl
=
"
var
"
;
address_space
=
"
storage
"
;
align
=
1
]
[
:
decl
=
"
var
"
;
address_space
=
"
storage
"
;
align
=
2
]
[
:
decl
=
"
var
"
;
address_space
=
"
storage
"
;
align
=
32
]
[
:
decl
=
"
var
"
;
address_space
=
"
uniform
"
;
align
=
"
alignment
"
]
[
:
decl
=
"
var
"
;
address_space
=
"
uniform
"
;
align
=
1
]
[
:
decl
=
"
var
"
;
address_space
=
"
uniform
"
;
align
=
2
]
[
:
decl
=
"
var
"
;
address_space
=
"
uniform
"
;
align
=
32
]
[
:
decl
=
"
var
"
;
address_space
=
"
workgroup
"
;
align
=
"
alignment
"
]
[
:
decl
=
"
var
"
;
address_space
=
"
workgroup
"
;
align
=
1
]
[
:
decl
=
"
var
"
;
address_space
=
"
workgroup
"
;
align
=
2
]
[
:
decl
=
"
var
"
;
address_space
=
"
workgroup
"
;
align
=
32
]
