[
align
.
wast
.
js
.
html
]
[
#
130
Test
that
WebAssembly
instantiation
succeeds
]
expected
:
FAIL
[
#
262
run
]
expected
:
FAIL
[
#
265
run
]
expected
:
FAIL
[
#
268
run
]
expected
:
FAIL
[
#
271
run
]
expected
:
FAIL
[
#
274
run
]
expected
:
FAIL
[
#
277
run
]
expected
:
FAIL
[
#
280
run
]
expected
:
FAIL
[
#
283
run
]
expected
:
FAIL
[
#
286
run
]
expected
:
FAIL
