[
call_indirect
.
wast
.
js
.
html
]
[
#
87
Test
that
WebAssembly
instantiation
succeeds
]
expected
:
FAIL
[
#
92
run
]
expected
:
FAIL
[
#
95
run
]
expected
:
FAIL
[
#
98
run
]
expected
:
FAIL
[
#
104
run
]
expected
:
FAIL
[
#
107
run
]
expected
:
FAIL
[
#
112
run
]
expected
:
FAIL
[
#
115
run
]
expected
:
FAIL
[
#
118
run
]
expected
:
FAIL
[
#
121
run
]
expected
:
FAIL
[
#
147
run
]
expected
:
FAIL
[
#
150
run
]
expected
:
FAIL
[
#
153
run
]
expected
:
FAIL
[
#
156
run
]
expected
:
FAIL
[
#
165
run
]
expected
:
FAIL
[
#
168
run
]
expected
:
FAIL
[
#
171
run
]
expected
:
FAIL
[
#
174
run
]
expected
:
FAIL
[
#
191
run
]
expected
:
FAIL
[
#
194
run
]
expected
:
FAIL
[
#
197
run
]
expected
:
FAIL
[
#
200
run
]
expected
:
FAIL
[
#
203
run
]
expected
:
FAIL
[
#
206
run
]
expected
:
FAIL
[
#
209
run
]
expected
:
FAIL
[
#
212
run
]
expected
:
FAIL
[
#
225
run
]
expected
:
FAIL
[
#
228
run
]
expected
:
FAIL
[
#
231
run
]
expected
:
FAIL
[
#
234
run
]
expected
:
FAIL
[
#
237
run
]
expected
:
FAIL
[
#
240
run
]
expected
:
FAIL
[
#
243
run
]
expected
:
FAIL
[
#
246
run
]
expected
:
FAIL
[
#
249
run
]
expected
:
FAIL
[
#
252
run
]
expected
:
FAIL
[
#
271
run
]
expected
:
FAIL
[
#
280
run
]
expected
:
FAIL
[
#
283
run
]
expected
:
FAIL
[
#
286
run
]
expected
:
FAIL
[
#
289
run
]
expected
:
FAIL
[
#
293
run
]
expected
:
FAIL
