[
float_literals
.
wast
.
js
.
html
]
[
#
105
Test
that
WebAssembly
instantiation
succeeds
]
expected
:
FAIL
[
#
186
run
]
expected
:
FAIL
[
#
189
run
]
expected
:
FAIL
[
#
192
run
]
expected
:
FAIL
[
#
195
run
]
expected
:
FAIL
[
#
198
run
]
expected
:
FAIL
[
#
201
run
]
expected
:
FAIL
[
#
204
run
]
expected
:
FAIL
[
#
207
run
]
expected
:
FAIL
[
#
210
run
]
expected
:
FAIL
[
#
213
run
]
expected
:
FAIL
[
#
216
run
]
expected
:
FAIL
[
#
219
run
]
expected
:
FAIL
[
#
222
run
]
expected
:
FAIL
[
#
225
run
]
expected
:
FAIL
[
#
228
run
]
expected
:
FAIL
[
#
231
run
]
expected
:
FAIL
[
#
234
run
]
expected
:
FAIL
[
#
237
run
]
expected
:
FAIL
[
#
240
run
]
expected
:
FAIL
[
#
243
run
]
expected
:
FAIL
[
#
248
run
]
expected
:
FAIL
