[
local_set
.
wast
.
js
.
html
]
[
#
42
Test
that
WebAssembly
instantiation
succeeds
]
expected
:
FAIL
[
#
51
run
]
expected
:
FAIL
[
#
54
run
]
expected
:
FAIL
[
#
66
run
]
expected
:
FAIL
[
#
69
run
]
expected
:
FAIL
