[
return
.
wast
.
js
.
html
]
[
#
30
Test
that
WebAssembly
instantiation
succeeds
]
expected
:
FAIL
[
#
39
run
]
expected
:
FAIL
[
#
42
run
]
expected
:
FAIL
[
#
46
run
]
expected
:
FAIL
[
#
88
run
]
expected
:
FAIL
[
#
96
run
]
expected
:
FAIL
