Classes
=
[
{
'
cid
'
:
'
{
a2568d74
-
be41
-
46a5
-
abfc
-
6dbab0b80f95
}
'
'
interfaces
'
:
[
'
nsIMLUtils
'
]
'
contract_ids
'
:
[
'
mozilla
.
org
/
ml
-
utils
;
1
'
]
'
type
'
:
'
mozilla
:
:
ml
:
:
MLUtils
'
'
headers
'
:
[
'
mozilla
/
ml
/
MLUtils
.
h
'
]
}
{
'
name
'
:
'
MLModelHub
'
'
cid
'
:
'
{
e381b167
-
cb68
-
429c
-
9d57
-
35acf9054505
}
'
'
contract_ids
'
:
[
'
mozilla
.
org
/
ml
-
modelhub
;
1
'
]
'
esModule
'
:
'
moz
-
src
:
/
/
/
toolkit
/
components
/
ml
/
MLModelHubService
.
sys
.
mjs
'
'
constructor
'
:
'
MLModelHubService
'
}
]
