[
html5lib
-
basics
.
html
]
[
Testcase
#
7
with
.
setHTMLUnsafe
(
"
<
table
>
<
b
>
a
<
/
b
>
bb
<
tr
>
<
td
>
y
"
)
]
expected
:
FAIL
[
Testcase
#
7
.
innerHTML
matches
.
setHTMLUnsafe
]
expected
:
FAIL
[
Testcase
#
8
with
.
setHTMLUnsafe
(
"
<
table
>
<
div
>
d
<
/
div
>
<
td
>
"
)
]
expected
:
FAIL
[
Testcase
#
8
.
innerHTML
matches
.
setHTMLUnsafe
]
expected
:
FAIL
