/
*
This
Source
Code
Form
is
subject
to
the
terms
of
the
Mozilla
Public
*
License
v
.
2
.
0
.
If
a
copy
of
the
MPL
was
not
distributed
with
this
*
file
You
can
obtain
one
at
http
:
/
/
mozilla
.
org
/
MPL
/
2
.
0
/
.
*
/
#
include
"
nsISupports
.
idl
"
interface
nsIURI
;
interface
nsIInputStream
;
[
scriptable
uuid
(
5799251f
-
5b55
-
4df7
-
a9e7
-
0c27812c469a
)
]
interface
nsISearchSubmission
:
nsISupports
{
/
*
*
*
The
POST
data
associated
with
a
search
submission
wrapped
in
a
MIME
*
input
stream
.
May
be
null
.
*
/
readonly
attribute
nsIInputStream
postData
;
/
*
*
*
The
URI
to
submit
a
search
to
.
*
/
readonly
attribute
nsIURI
uri
;
}
;
