[
wheel
-
event
-
composed
.
html
]
expected
:
if
os
=
=
"
linux
"
:
[
OK
TIMEOUT
]
#
Bug
2058132
-
timeout
with
Nova
design
enabled
if
os
=
=
"
mac
"
:
[
OK
TIMEOUT
]
#
Bug
2058132
-
timeout
with
Nova
design
enabled
if
os
=
=
"
win
"
:
[
OK
TIMEOUT
]
#
Bug
2058132
-
timeout
with
Nova
design
enabled
[
wheel
event
must
be
composed
]
expected
:
if
os
=
=
"
linux
"
:
[
PASS
TIMEOUT
]
#
Bug
2058132
-
timeout
with
Nova
design
enabled
if
os
=
=
"
mac
"
:
[
PASS
TIMEOUT
]
#
Bug
2058132
-
timeout
with
Nova
design
enabled
if
os
=
=
"
win
"
:
[
PASS
TIMEOUT
]
#
Bug
2058132
-
timeout
with
Nova
design
enabled
