[
multiple
-
content
-
disposition
.
tentative
.
h2
.
window
.
html
]
#
Bug
1982182
[
HTTP
/
2
:
identical
duplicate
Content
-
Disposition
headers
are
combined
]
expected
:
FAIL
[
HTTP
/
2
:
differing
duplicate
Content
-
Disposition
headers
are
not
a
network
error
]
expected
:
FAIL
[
HTTP
/
2
:
differing
duplicate
Content
-
Disposition
headers
are
combined
]
expected
:
FAIL
