[
table_copy
.
wast
.
js
.
html
]
[
#
56
Test
that
WebAssembly
instantiation
succeeds
]
expected
:
FAIL
[
#
59
run
]
expected
:
FAIL
[
#
122
run
]
expected
:
FAIL
[
#
185
run
]
expected
:
FAIL
[
#
248
run
]
expected
:
FAIL
[
#
311
run
]
expected
:
FAIL
[
#
374
run
]
expected
:
FAIL
[
#
437
run
]
expected
:
FAIL
[
#
500
run
]
expected
:
FAIL
[
#
563
run
]
expected
:
FAIL
[
#
626
run
]
expected
:
FAIL
[
#
689
run
]
expected
:
FAIL
[
#
752
run
]
expected
:
FAIL
[
#
815
run
]
expected
:
FAIL
[
#
878
run
]
expected
:
FAIL
[
#
941
run
]
expected
:
FAIL
[
#
1004
run
]
expected
:
FAIL
[
#
1067
run
]
expected
:
FAIL
[
#
1130
run
]
expected
:
FAIL
