[
data_drop0
.
wast
.
js
.
html
]
[
#
5
Test
that
WebAssembly
instantiation
succeeds
]
expected
:
FAIL
[
#
6
run
]
expected
:
FAIL
[
#
7
run
]
expected
:
FAIL
[
#
8
run
]
expected
:
FAIL
[
#
11
run
]
expected
:
FAIL
[
#
12
run
]
expected
:
FAIL
[
#
15
run
]
expected
:
FAIL
