[
memory_copy0
.
wast
.
js
.
html
]
[
#
5
Test
that
WebAssembly
instantiation
succeeds
]
expected
:
FAIL
[
#
6
run
]
expected
:
FAIL
[
#
13
run
]
expected
:
FAIL
[
#
20
run
]
expected
:
FAIL
[
#
28
run
]
expected
:
FAIL
[
#
29
run
]
expected
:
FAIL
[
#
30
run
]
expected
:
FAIL
[
#
31
run
]
expected
:
FAIL
