[
cts
.
https
.
html
?
q
=
webgpu
:
shader
execution
expression
call
builtin
bufferView
:
array_length
functions
:
*
]
[
:
type
=
"
S
"
;
aspace
=
"
storage
"
]
[
:
type
=
"
S
"
;
aspace
=
"
uniform
"
]
[
:
type
=
"
S
"
;
aspace
=
"
workgroup
"
]
[
:
type
=
"
S_arr
"
;
aspace
=
"
storage
"
]
[
:
type
=
"
S_arr
"
;
aspace
=
"
uniform
"
]
[
:
type
=
"
S_arr
"
;
aspace
=
"
workgroup
"
]
[
:
type
=
"
T
"
;
aspace
=
"
storage
"
]
[
:
type
=
"
T
"
;
aspace
=
"
uniform
"
]
[
:
type
=
"
T
"
;
aspace
=
"
workgroup
"
]
[
:
type
=
"
T_arr
"
;
aspace
=
"
storage
"
]
[
:
type
=
"
T_arr
"
;
aspace
=
"
uniform
"
]
[
:
type
=
"
T_arr
"
;
aspace
=
"
workgroup
"
]
[
:
type
=
"
array_S_2
"
;
aspace
=
"
storage
"
]
[
:
type
=
"
array_S_2
"
;
aspace
=
"
uniform
"
]
[
:
type
=
"
array_S_2
"
;
aspace
=
"
workgroup
"
]
[
:
type
=
"
array_T_2
"
;
aspace
=
"
storage
"
]
[
:
type
=
"
array_T_2
"
;
aspace
=
"
uniform
"
]
[
:
type
=
"
array_T_2
"
;
aspace
=
"
workgroup
"
]
[
:
type
=
"
array_f16_6
"
;
aspace
=
"
storage
"
]
[
:
type
=
"
array_f16_6
"
;
aspace
=
"
uniform
"
]
[
:
type
=
"
array_f16_6
"
;
aspace
=
"
workgroup
"
]
[
:
type
=
"
array_u32_4
"
;
aspace
=
"
storage
"
]
[
:
type
=
"
array_u32_4
"
;
aspace
=
"
uniform
"
]
[
:
type
=
"
array_u32_4
"
;
aspace
=
"
workgroup
"
]
[
:
type
=
"
array_vec2f_2
"
;
aspace
=
"
storage
"
]
[
:
type
=
"
array_vec2f_2
"
;
aspace
=
"
uniform
"
]
[
:
type
=
"
array_vec2f_2
"
;
aspace
=
"
workgroup
"
]
[
:
type
=
"
f16
"
;
aspace
=
"
storage
"
]
[
:
type
=
"
f16
"
;
aspace
=
"
uniform
"
]
[
:
type
=
"
f16
"
;
aspace
=
"
workgroup
"
]
[
:
type
=
"
mat2x2f
"
;
aspace
=
"
storage
"
]
[
:
type
=
"
mat2x2f
"
;
aspace
=
"
uniform
"
]
[
:
type
=
"
mat2x2f
"
;
aspace
=
"
workgroup
"
]
[
:
type
=
"
mat2x3f
"
;
aspace
=
"
storage
"
]
[
:
type
=
"
mat2x3f
"
;
aspace
=
"
uniform
"
]
[
:
type
=
"
mat2x3f
"
;
aspace
=
"
workgroup
"
]
[
:
type
=
"
mat2x4f
"
;
aspace
=
"
storage
"
]
[
:
type
=
"
mat2x4f
"
;
aspace
=
"
uniform
"
]
[
:
type
=
"
mat2x4f
"
;
aspace
=
"
workgroup
"
]
[
:
type
=
"
mat3x2h
"
;
aspace
=
"
storage
"
]
[
:
type
=
"
mat3x2h
"
;
aspace
=
"
uniform
"
]
[
:
type
=
"
mat3x2h
"
;
aspace
=
"
workgroup
"
]
[
:
type
=
"
mat3x3h
"
;
aspace
=
"
storage
"
]
[
:
type
=
"
mat3x3h
"
;
aspace
=
"
uniform
"
]
[
:
type
=
"
mat3x3h
"
;
aspace
=
"
workgroup
"
]
[
:
type
=
"
mat3x4h
"
;
aspace
=
"
storage
"
]
[
:
type
=
"
mat3x4h
"
;
aspace
=
"
uniform
"
]
[
:
type
=
"
mat3x4h
"
;
aspace
=
"
workgroup
"
]
[
:
type
=
"
mat4x2f
"
;
aspace
=
"
storage
"
]
[
:
type
=
"
mat4x2f
"
;
aspace
=
"
uniform
"
]
[
:
type
=
"
mat4x2f
"
;
aspace
=
"
workgroup
"
]
[
:
type
=
"
mat4x3f
"
;
aspace
=
"
storage
"
]
[
:
type
=
"
mat4x3f
"
;
aspace
=
"
uniform
"
]
[
:
type
=
"
mat4x3f
"
;
aspace
=
"
workgroup
"
]
[
:
type
=
"
mat4x4f
"
;
aspace
=
"
storage
"
]
[
:
type
=
"
mat4x4f
"
;
aspace
=
"
uniform
"
]
[
:
type
=
"
mat4x4f
"
;
aspace
=
"
workgroup
"
]
[
:
type
=
"
u32
"
;
aspace
=
"
storage
"
]
[
:
type
=
"
u32
"
;
aspace
=
"
uniform
"
]
[
:
type
=
"
u32
"
;
aspace
=
"
workgroup
"
]
[
:
type
=
"
vec2f
"
;
aspace
=
"
storage
"
]
[
:
type
=
"
vec2f
"
;
aspace
=
"
uniform
"
]
[
:
type
=
"
vec2f
"
;
aspace
=
"
workgroup
"
]
[
:
type
=
"
vec2h
"
;
aspace
=
"
storage
"
]
[
:
type
=
"
vec2h
"
;
aspace
=
"
uniform
"
]
[
:
type
=
"
vec2h
"
;
aspace
=
"
workgroup
"
]
[
:
type
=
"
vec3h
"
;
aspace
=
"
storage
"
]
[
:
type
=
"
vec3h
"
;
aspace
=
"
uniform
"
]
[
:
type
=
"
vec3h
"
;
aspace
=
"
workgroup
"
]
[
:
type
=
"
vec3i
"
;
aspace
=
"
storage
"
]
[
:
type
=
"
vec3i
"
;
aspace
=
"
uniform
"
]
[
:
type
=
"
vec3i
"
;
aspace
=
"
workgroup
"
]
[
:
type
=
"
vec4h
"
;
aspace
=
"
storage
"
]
[
:
type
=
"
vec4h
"
;
aspace
=
"
uniform
"
]
[
:
type
=
"
vec4h
"
;
aspace
=
"
workgroup
"
]
[
:
type
=
"
vec4u
"
;
aspace
=
"
storage
"
]
[
:
type
=
"
vec4u
"
;
aspace
=
"
uniform
"
]
[
:
type
=
"
vec4u
"
;
aspace
=
"
workgroup
"
]
[
cts
.
https
.
html
?
q
=
webgpu
:
shader
execution
expression
call
builtin
bufferView
:
array_length
:
*
]
[
:
type
=
"
S
"
;
aspace
=
"
storage
"
]
[
:
type
=
"
S
"
;
aspace
=
"
uniform
"
]
[
:
type
=
"
S
"
;
aspace
=
"
workgroup
"
]
[
:
type
=
"
S_arr
"
;
aspace
=
"
storage
"
]
[
:
type
=
"
S_arr
"
;
aspace
=
"
uniform
"
]
[
:
type
=
"
S_arr
"
;
aspace
=
"
workgroup
"
]
[
:
type
=
"
T
"
;
aspace
=
"
storage
"
]
[
:
type
=
"
T
"
;
aspace
=
"
uniform
"
]
[
:
type
=
"
T
"
;
aspace
=
"
workgroup
"
]
[
:
type
=
"
T_arr
"
;
aspace
=
"
storage
"
]
[
:
type
=
"
T_arr
"
;
aspace
=
"
uniform
"
]
[
:
type
=
"
T_arr
"
;
aspace
=
"
workgroup
"
]
[
:
type
=
"
array_S_2
"
;
aspace
=
"
storage
"
]
[
:
type
=
"
array_S_2
"
;
aspace
=
"
uniform
"
]
[
:
type
=
"
array_S_2
"
;
aspace
=
"
workgroup
"
]
[
:
type
=
"
array_T_2
"
;
aspace
=
"
storage
"
]
[
:
type
=
"
array_T_2
"
;
aspace
=
"
uniform
"
]
[
:
type
=
"
array_T_2
"
;
aspace
=
"
workgroup
"
]
[
:
type
=
"
array_f16_6
"
;
aspace
=
"
storage
"
]
[
:
type
=
"
array_f16_6
"
;
aspace
=
"
uniform
"
]
[
:
type
=
"
array_f16_6
"
;
aspace
=
"
workgroup
"
]
[
:
type
=
"
array_u32_4
"
;
aspace
=
"
storage
"
]
[
:
type
=
"
array_u32_4
"
;
aspace
=
"
uniform
"
]
[
:
type
=
"
array_u32_4
"
;
aspace
=
"
workgroup
"
]
[
:
type
=
"
array_vec2f_2
"
;
aspace
=
"
storage
"
]
[
:
type
=
"
array_vec2f_2
"
;
aspace
=
"
uniform
"
]
[
:
type
=
"
array_vec2f_2
"
;
aspace
=
"
workgroup
"
]
[
:
type
=
"
f16
"
;
aspace
=
"
storage
"
]
[
:
type
=
"
f16
"
;
aspace
=
"
uniform
"
]
[
:
type
=
"
f16
"
;
aspace
=
"
workgroup
"
]
[
:
type
=
"
mat2x2f
"
;
aspace
=
"
storage
"
]
[
:
type
=
"
mat2x2f
"
;
aspace
=
"
uniform
"
]
[
:
type
=
"
mat2x2f
"
;
aspace
=
"
workgroup
"
]
[
:
type
=
"
mat2x3f
"
;
aspace
=
"
storage
"
]
[
:
type
=
"
mat2x3f
"
;
aspace
=
"
uniform
"
]
[
:
type
=
"
mat2x3f
"
;
aspace
=
"
workgroup
"
]
[
:
type
=
"
mat2x4f
"
;
aspace
=
"
storage
"
]
[
:
type
=
"
mat2x4f
"
;
aspace
=
"
uniform
"
]
[
:
type
=
"
mat2x4f
"
;
aspace
=
"
workgroup
"
]
[
:
type
=
"
mat3x2h
"
;
aspace
=
"
storage
"
]
[
:
type
=
"
mat3x2h
"
;
aspace
=
"
uniform
"
]
[
:
type
=
"
mat3x2h
"
;
aspace
=
"
workgroup
"
]
[
:
type
=
"
mat3x3h
"
;
aspace
=
"
storage
"
]
[
:
type
=
"
mat3x3h
"
;
aspace
=
"
uniform
"
]
[
:
type
=
"
mat3x3h
"
;
aspace
=
"
workgroup
"
]
[
:
type
=
"
mat3x4h
"
;
aspace
=
"
storage
"
]
[
:
type
=
"
mat3x4h
"
;
aspace
=
"
uniform
"
]
[
:
type
=
"
mat3x4h
"
;
aspace
=
"
workgroup
"
]
[
:
type
=
"
mat4x2f
"
;
aspace
=
"
storage
"
]
[
:
type
=
"
mat4x2f
"
;
aspace
=
"
uniform
"
]
[
:
type
=
"
mat4x2f
"
;
aspace
=
"
workgroup
"
]
[
:
type
=
"
mat4x3f
"
;
aspace
=
"
storage
"
]
[
:
type
=
"
mat4x3f
"
;
aspace
=
"
uniform
"
]
[
:
type
=
"
mat4x3f
"
;
aspace
=
"
workgroup
"
]
[
:
type
=
"
mat4x4f
"
;
aspace
=
"
storage
"
]
[
:
type
=
"
mat4x4f
"
;
aspace
=
"
uniform
"
]
[
:
type
=
"
mat4x4f
"
;
aspace
=
"
workgroup
"
]
[
:
type
=
"
u32
"
;
aspace
=
"
storage
"
]
[
:
type
=
"
u32
"
;
aspace
=
"
uniform
"
]
[
:
type
=
"
u32
"
;
aspace
=
"
workgroup
"
]
[
:
type
=
"
vec2f
"
;
aspace
=
"
storage
"
]
[
:
type
=
"
vec2f
"
;
aspace
=
"
uniform
"
]
[
:
type
=
"
vec2f
"
;
aspace
=
"
workgroup
"
]
[
:
type
=
"
vec2h
"
;
aspace
=
"
storage
"
]
[
:
type
=
"
vec2h
"
;
aspace
=
"
uniform
"
]
[
:
type
=
"
vec2h
"
;
aspace
=
"
workgroup
"
]
[
:
type
=
"
vec3h
"
;
aspace
=
"
storage
"
]
[
:
type
=
"
vec3h
"
;
aspace
=
"
uniform
"
]
[
:
type
=
"
vec3h
"
;
aspace
=
"
workgroup
"
]
[
:
type
=
"
vec3i
"
;
aspace
=
"
storage
"
]
[
:
type
=
"
vec3i
"
;
aspace
=
"
uniform
"
]
[
:
type
=
"
vec3i
"
;
aspace
=
"
workgroup
"
]
[
:
type
=
"
vec4h
"
;
aspace
=
"
storage
"
]
[
:
type
=
"
vec4h
"
;
aspace
=
"
uniform
"
]
[
:
type
=
"
vec4h
"
;
aspace
=
"
workgroup
"
]
[
:
type
=
"
vec4u
"
;
aspace
=
"
storage
"
]
[
:
type
=
"
vec4u
"
;
aspace
=
"
uniform
"
]
[
:
type
=
"
vec4u
"
;
aspace
=
"
workgroup
"
]
[
cts
.
https
.
html
?
q
=
webgpu
:
shader
execution
expression
call
builtin
bufferView
:
read
:
*
]
[
:
base_type
=
"
f16
"
]
[
:
base_type
=
"
f32
"
]
[
:
base_type
=
"
i32
"
]
[
:
base_type
=
"
u32
"
]
[
cts
.
https
.
html
?
q
=
webgpu
:
shader
execution
expression
call
builtin
bufferView
:
read_layout
:
*
]
[
:
case
=
"
array_stride_size
"
]
[
:
case
=
"
mat2x2f_align8
"
]
[
:
case
=
"
mat2x2f_size
"
]
[
:
case
=
"
mat2x2h_size
"
]
[
:
case
=
"
mat2x3f_size
"
]
[
:
case
=
"
mat2x3h_size
"
]
[
:
case
=
"
mat2x4f_size
"
]
[
:
case
=
"
mat2x4h_align8
"
]
[
:
case
=
"
mat2x4h_size
"
]
[
:
case
=
"
mat3x2f_size
"
]
[
:
case
=
"
mat3x2h_align4
"
]
[
:
case
=
"
mat3x3f_align16
"
]
[
:
case
=
"
mat3x3f_size
"
]
[
:
case
=
"
mat3x4f_size
"
]
[
:
case
=
"
mat4x2h_size
"
]
[
:
case
=
"
mat4x3h_align8
"
]
[
:
case
=
"
mat4x3h_size
"
]
[
:
case
=
"
mat4x4f_align16
"
]
[
:
case
=
"
mat4x4h_size
"
]
[
:
case
=
"
size80
"
]
[
:
case
=
"
struct_align32
"
]
[
:
case
=
"
struct_double_align
"
]
[
:
case
=
"
struct_inner_align
"
]
[
:
case
=
"
struct_inner_size
"
]
[
:
case
=
"
struct_inner_size_and_align
"
]
[
:
case
=
"
struct_override_size
"
]
[
:
case
=
"
struct_size_roundup
"
]
[
:
case
=
"
vec2h_align4
"
]
[
:
case
=
"
vec2u_align8
"
]
[
:
case
=
"
vec3h_align8
"
]
[
:
case
=
"
vec3h_size6
"
]
[
:
case
=
"
vec3i_size12
"
]
[
:
case
=
"
vec3u_align16
"
]
[
:
case
=
"
vec4h_align8
"
]
[
:
case
=
"
vec4u_align16
"
]
[
cts
.
https
.
html
?
q
=
webgpu
:
shader
execution
expression
call
builtin
bufferView
:
write
:
*
]
[
:
base_type
=
"
f16
"
]
[
:
base_type
=
"
f32
"
]
[
:
base_type
=
"
i32
"
]
[
:
base_type
=
"
u32
"
]
[
cts
.
https
.
html
?
q
=
webgpu
:
shader
execution
expression
call
builtin
bufferView
:
write_layout
:
*
]
[
:
case
=
"
array_stride_size
"
]
[
:
case
=
"
mat2x2f_align8
"
]
[
:
case
=
"
mat2x2f_size
"
]
[
:
case
=
"
mat2x2h_size
"
]
[
:
case
=
"
mat2x3f_size
"
]
[
:
case
=
"
mat2x3h_size
"
]
[
:
case
=
"
mat2x4f_size
"
]
[
:
case
=
"
mat2x4h_align8
"
]
[
:
case
=
"
mat2x4h_size
"
]
[
:
case
=
"
mat3x2f_size
"
]
[
:
case
=
"
mat3x2h_align4
"
]
[
:
case
=
"
mat3x3f_align16
"
]
[
:
case
=
"
mat3x3f_size
"
]
[
:
case
=
"
mat3x4f_size
"
]
[
:
case
=
"
mat4x2h_size
"
]
[
:
case
=
"
mat4x3h_align8
"
]
[
:
case
=
"
mat4x3h_size
"
]
[
:
case
=
"
mat4x4f_align16
"
]
[
:
case
=
"
mat4x4h_size
"
]
[
:
case
=
"
size80
"
]
[
:
case
=
"
struct_align32
"
]
[
:
case
=
"
struct_double_align
"
]
[
:
case
=
"
struct_inner_align
"
]
[
:
case
=
"
struct_inner_size
"
]
[
:
case
=
"
struct_inner_size_and_align
"
]
[
:
case
=
"
struct_override_size
"
]
[
:
case
=
"
struct_size_roundup
"
]
[
:
case
=
"
vec2h_align4
"
]
[
:
case
=
"
vec2u_align8
"
]
[
:
case
=
"
vec3h_align8
"
]
[
:
case
=
"
vec3h_size6
"
]
[
:
case
=
"
vec3i_size12
"
]
[
:
case
=
"
vec3u_align16
"
]
[
:
case
=
"
vec4h_align8
"
]
[
:
case
=
"
vec4u_align16
"
]
