[
anchor
-
scroll
-
single
-
axis
-
default
-
anchor
.
html
]
[
inner
scrollable
in
y
only
:
#
outer
'
s
x
scroll
is
still
compensated
]
expected
:
FAIL
[
inner
scrollable
in
x
only
:
#
outer
'
s
y
scroll
is
still
compensated
]
expected
:
FAIL
