[
cmyk
-
basic
-
conversion
-
reftest
.
html
]
fuzzy
:
maxDifference
=
0
-
60
;
totalPixels
=
0
-
4789
expected
:
if
release_or_beta
:
FAIL
if
(
os
=
=
"
mac
"
)
and
not
debug
and
(
version
=
=
"
OS
X
14
.
7
.
5
"
)
:
[
PASS
FAIL
]
if
(
os
=
=
"
android
"
)
and
not
debug
:
[
PASS
FAIL
]
