#
-
*
-
Mode
:
python
;
indent
-
tabs
-
mode
:
nil
;
tab
-
width
:
4
-
*
-
#
vim
:
set
filetype
=
python
:
#
This
Source
Code
Form
is
subject
to
the
terms
of
the
Mozilla
Public
#
License
v
.
2
.
0
.
If
a
copy
of
the
MPL
was
not
distributed
with
this
#
file
You
can
obtain
one
at
http
:
/
/
mozilla
.
org
/
MPL
/
2
.
0
/
.
Classes
=
[
{
"
cid
"
:
"
{
f330141f
-
9b06
-
4ebd
-
baa4
-
df932e9eb78e
}
"
"
contract_ids
"
:
[
"
mozilla
.
org
/
ml
/
model
-
resolver
;
1
?
task
=
speech
-
recognition
"
]
"
type
"
:
"
mozilla
:
:
dom
:
:
SpeechModelResolver
"
"
headers
"
:
[
"
/
dom
/
media
/
webspeech
/
recognition
/
SpeechModelResolver
.
h
"
]
"
processes
"
:
ProcessSelector
.
MAIN_PROCESS_ONLY
}
]
