#
This
Source
Code
Form
is
subject
to
the
terms
of
the
Mozilla
Public
#
License
v
.
2
.
0
.
If
a
copy
of
the
MPL
was
not
distributed
with
this
#
file
You
can
obtain
one
at
http
:
/
/
mozilla
.
org
/
MPL
/
2
.
0
/
.
Classes
=
[
{
'
cid
'
:
'
{
ecd1af44
-
241a
-
4b61
-
96ab
-
fdfa2b8b0fbf
}
'
'
contract_ids
'
:
[
'
mozilla
.
org
/
site
-
container
-
service
;
1
'
]
'
esModule
'
:
'
moz
-
src
:
/
/
/
toolkit
/
components
/
contextualidentity
/
ContextualIdentityService
.
sys
.
mjs
'
'
constructor
'
:
'
SiteContainerService
'
}
]
